version: "3"
services:
  client:
    container_name: todo-app_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_client
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - "API_URL=http://localhost:5000/api"
    depends_on:
      - server
    networks:
      - todo-app-network
  server:
    container_name: todo-app_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_server
    ports:
      - ${SERVER_PORT}:5000
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - todo-app-network
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    command: mongod --noauth
    networks:
      - todo-app-network

networks:
    todo-app-network:
        driver: bridge